name = "2022-NOV Pack"
author = "me"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd419d76eea519d24116189a5b202bd6da4da6bb05c7de51953cb48ae842054e"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.20"
