name = "2022-NOV Pack"
author = "me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd035951c437b86b9a5dd7566781a42fddf9e5d86942085bf997b63cee31d154"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.20"
